### ISSUE TITLE
ScalaTest: Tests are not run when `verifyPacts` is called asynchronously

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [jbwheatley/pact4s#17] opened 2021-06-03 21:32 UTC
I need to start up a server which relies on [testcontainers](https://github.com/testcontainers/testcontainers-scala) before I can provide the correct port in the `ProviderInfoBuilder` -- this forces me to call `verifyPacts()` asynchronously (from `afterContainersStart`), but this results in the test suite exiting without running any tests.

As a workaround for now, I can just put a dummy test case in there, but I wonder if there is a better solution.

**Comment by solarmosaic-kflorence** [comment] 2021-06-03 22:51
Seems like I have a separate problem here as well, I cannot use the containers except inside a test, but I currently need to reference the container outside of a test for `ProviderInfoBuilder` -- unfortunately in my case this is because the Lagom framework does not allow me to specify a port, it always chooses a random one: https://github.com/lagom/lagom/issues/3168

Not sure how to work around this because the provider is needed to get the consumers. I wish the local provider service could be evaluated lazily, since it isn't really needed until inside the tests... 🤔

**Comment by jbwheatley** [comment] 2021-06-09 08:21
So perhaps part of the problem is how i set up `verifyPacts()`, in that it auto-generates tests for the user. Maybe it would be better that you had to explicitly write 
```scala
test("verification of provider pacts") {
  verifyPacts()
}
``` 

I think that would solve some of these issues.

**Comment by jbwheatley** [comment] 2021-06-10 16:40
this should be fixed in `v0.0.9`. Will reopen if not

**Closed by jbwheatley** 2021-06-10 16:40 UTC
Labels: verification
